site_name: IZrO Literature
theme:
  name: material

markdown_extensions:
  - tables
  - attr_list
  - md_in_html

extra_css:
  - https://cdn.jsdelivr.net/npm/tabulator-tables/dist/css/tabulator.min.css
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/papaparse@5.4.1/papaparse.min.js
  - https://cdn.jsdelivr.net/npm/tabulator-tables/dist/js/tabulator.min.js
  - javascripts/tabulator.js

nav:
  - Home: index.md
  - Papers: papers.md
  - Reported Data: reported-data.md
